### ISSUE TITLE
Dimension Error for 2D with Mutual Information

### ISSUE THREAD

**Issue by notuntoward** [LauritzR/Parallel-Principal-Feature-Analysis#2]
If I run the 2D example in the README, but with `calculate_mutual_information=True`, I get an error.  Is this expected?

**Code Causing Error**
```
from parallel_principal_feature_analysis import par_pfa  

# get example dir
import parallel_principal_feature_analysis
import pathlib as pl
exampDir = (pl.Path(parallel_principal_feature_analysis.__file__)
            .parent.parent.parent / 'example')

examp3FNm = exampDir / "test_PFA_2dim_cont_y.csv" # 2D example

par_pfa(examp3FNm, number_output_functions=2, calculate_mutual_information=True)
```

**Error Message:**

> Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?03429d53-1dc9-4616-8ad4-7d217aae5039)---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Cell In[20], line 1
> ----> 1 par_pfa(examp3FNm, number_output_functions=2, calculate_mutual_information=True)
> 
> File [~\OneDrive\share\repos\Parallel-Principal-Feature-Analysis\src\parallel_principal_feature_analysis\execute_PFA.py:80](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/scott/OneDrive/share/ds-experimental/scotto/lib/python/sandbox/princFeatAnal/~/OneDrive/share/repos/Parallel-Principal-Feature-Analysis/src/parallel_principal_feature_analysis/execute_PFA.py:80), in par_pfa(path, number_output_functions, number_sweeps, cluster_size, alpha, min_n_datapoints_a_bin, shuffle_feature_numbers, frac, calculate_mutual_information, basis_log_mutual_information)
>      78 if calculate_mutual_information==1:
>      79     print("Calculating mutual information")
> ---> 80     list_data_frame_feature_mutual_information=get_mutual_information(data,number_output_functions,pf_from_intersection,min_n_datapoints_a_bin,basis_log_mutual_information)
>      81     for i in range(0,len(list_data_frame_feature_mutual_information)):
>      82         print(list_data_frame_feature_mutual_information[i])
> 
> File [~\OneDrive\share\repos\Parallel-Principal-Feature-Analysis\src\parallel_principal_feature_analysis\get_mutual_information.py:93](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/scott/OneDrive/share/ds-experimental/scotto/lib/python/sandbox/princFeatAnal/~/OneDrive/share/repos/Parallel-Principal-Feature-Analysis/src/parallel_principal_feature_analysis/get_mutual_information.py:93), in get_mutual_information(data, number_output_functions, list_variables, min_n_datapoints_a_bin, basis_log_mutual_information)
>      91     else:
>      92         mutual_info[0,j-number_output_functions+1]=np.sum(np.array(list(map(make_summand_from_frequencies,freq_data_product.flatten().tolist(),expfreq.flatten().tolist()))))
> ---> 93 pd_mutual_information = pd.DataFrame({"index feature": id_features, "mutual information": mutual_info.tolist()[0]})
>      94 pd_mutual_information['index feature'] = pd_mutual_information['index feature'].astype(int)
>      95 list_of_data_frames.append(pd_mutual_information)
> 
> File [c:\Users\scott\miniconda3\lib\site-packages\pandas\core\frame.py:664](file:///C:/Users/scott/miniconda3/lib/site-packages/pandas/core/frame.py:664), in DataFrame.__init__(self, data, index, columns, dtype, copy)
>     658     mgr = self._init_mgr(
>     659         data, axes={"index": index, "columns": columns}, dtype=dtype, copy=copy
>     660     )
>     662 elif isinstance(data, dict):
>     663     # GH#38939 de facto copy defaults to False only in non-dict cases
> ...
>     669     raise ValueError(
>     670         "Mixing dicts with non-Series may lead to ambiguous ordering."
>     671     )
> 
> ValueError: All arrays must be of the same length

**Comment by LauritzR** [comment]
Thank you for the heads up! The issue should be fixed now.

**Comment by notuntoward** [comment]
Thanks for the quick fix!  Could you offer some advice?  I'd like to try
this out in an sklearn pipeline, which would mean, at a minimum, routing
all the interface through function parameters instead files.  Could you
suggest what I should look out for, what I might inadvertently break?

**Comment by LauritzR** [comment]
Can you maybe elaborate further, what you are trying to do? 

You can rewrite the code locally so it takes the data itself as input and not the file path. You have to be careful with the required data format, transposing might be necessary. You might want to wrap the PFA in another function which takes the data, transposes it, feeds it into the PFA and filters and returns the principal features afterwards.
I hope this helps. Feel free to let me know if anything does or does not work!
